services:
  myapp:
    build: .
    container_name: oauth2-gcp-example
    ports:
      - "${PAYARA_HTTP_PORT}:8080"
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_SECRET_ID: ${OAUTH_SECRET_ID}